/* tslint:disable */
/* eslint-disable */
/**
 * OpenHolidays API v1
 * Open Data API for public and school holidays
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LocalizedText } from './LocalizedText';
import {
    LocalizedTextFromJSON,
    LocalizedTextFromJSONTyped,
    LocalizedTextToJSON,
    LocalizedTextToJSONTyped,
} from './LocalizedText';

/**
 * Representation of a country as defined in ISO 3166-1
 * @export
 * @interface CountryResponse
 */
export interface CountryResponse {
    /**
     * ISO 3166-1 country code
     * @type {string}
     * @memberof CountryResponse
     */
    isoCode: string;
    /**
     * Localized country names
     * @type {Array<LocalizedText>}
     * @memberof CountryResponse
     */
    name: Array<LocalizedText>;
    /**
     * Official ISO-639-1 language codes
     * @type {Array<string>}
     * @memberof CountryResponse
     */
    officialLanguages: Array<string>;
}

/**
 * Check if a given object implements the CountryResponse interface.
 */
export function instanceOfCountryResponse(value: object): value is CountryResponse {
    if (!('isoCode' in value) || value['isoCode'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('officialLanguages' in value) || value['officialLanguages'] === undefined) return false;
    return true;
}

export function CountryResponseFromJSON(json: any): CountryResponse {
    return CountryResponseFromJSONTyped(json, false);
}

export function CountryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CountryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'isoCode': json['isoCode'],
        'name': ((json['name'] as Array<any>).map(LocalizedTextFromJSON)),
        'officialLanguages': json['officialLanguages'],
    };
}

export function CountryResponseToJSON(json: any): CountryResponse {
    return CountryResponseToJSONTyped(json, false);
}

export function CountryResponseToJSONTyped(value?: CountryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isoCode': value['isoCode'],
        'name': ((value['name'] as Array<any>).map(LocalizedTextToJSON)),
        'officialLanguages': value['officialLanguages'],
    };
}

