/* tslint:disable */
/* eslint-disable */
/**
 * OpenHolidays API v1
 * Open Data API for public and school holidays
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Representation of a country reference
 * @export
 * @interface CountryReference
 */
export interface CountryReference {
    /**
     * Country ISO code
     * @type {string}
     * @memberof CountryReference
     */
    isoCode: string;
}

/**
 * Check if a given object implements the CountryReference interface.
 */
export function instanceOfCountryReference(value: object): value is CountryReference {
    if (!('isoCode' in value) || value['isoCode'] === undefined) return false;
    return true;
}

export function CountryReferenceFromJSON(json: any): CountryReference {
    return CountryReferenceFromJSONTyped(json, false);
}

export function CountryReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CountryReference {
    if (json == null) {
        return json;
    }
    return {
        
        'isoCode': json['isoCode'],
    };
}

export function CountryReferenceToJSON(json: any): CountryReference {
    return CountryReferenceToJSONTyped(json, false);
}

export function CountryReferenceToJSONTyped(value?: CountryReference | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isoCode': value['isoCode'],
    };
}

