/* tslint:disable */
/* eslint-disable */
/**
 * OpenHolidays API v1
 * Open Data API for public and school holidays
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Type of holiday
 * @export
 */
export const HolidayType = {
    Public: 'Public',
    Bank: 'Bank',
    Optional: 'Optional',
    School: 'School',
    BackToSchool: 'BackToSchool',
    EndOfLessons: 'EndOfLessons'
} as const;
export type HolidayType = typeof HolidayType[keyof typeof HolidayType];


export function instanceOfHolidayType(value: any): boolean {
    for (const key in HolidayType) {
        if (Object.prototype.hasOwnProperty.call(HolidayType, key)) {
            if (HolidayType[key as keyof typeof HolidayType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function HolidayTypeFromJSON(json: any): HolidayType {
    return HolidayTypeFromJSONTyped(json, false);
}

export function HolidayTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): HolidayType {
    return json as HolidayType;
}

export function HolidayTypeToJSON(value?: HolidayType | null): any {
    return value as any;
}

export function HolidayTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): HolidayType {
    return value as HolidayType;
}

