/* tslint:disable */
/* eslint-disable */
/**
 * OpenHolidays API v1
 * Open Data API for public and school holidays
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A localized text string
 * @export
 * @interface LocalizedText
 */
export interface LocalizedText {
    /**
     * ISO-639-1 language code
     * @type {string}
     * @memberof LocalizedText
     */
    language: string;
    /**
     * The localized text
     * @type {string}
     * @memberof LocalizedText
     */
    text: string;
}

/**
 * Check if a given object implements the LocalizedText interface.
 */
export function instanceOfLocalizedText(value: object): value is LocalizedText {
    if (!('language' in value) || value['language'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function LocalizedTextFromJSON(json: any): LocalizedText {
    return LocalizedTextFromJSONTyped(json, false);
}

export function LocalizedTextFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocalizedText {
    if (json == null) {
        return json;
    }
    return {
        
        'language': json['language'],
        'text': json['text'],
    };
}

export function LocalizedTextToJSON(json: any): LocalizedText {
    return LocalizedTextToJSONTyped(json, false);
}

export function LocalizedTextToJSONTyped(value?: LocalizedText | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'language': value['language'],
        'text': value['text'],
    };
}

