/* tslint:disable */
/* eslint-disable */
/**
 * OpenHolidays API v1
 * Open Data API for public and school holidays
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Regional scope of a holdiay
 * @export
 */
export const RegionalScope = {
    National: 'National',
    Regional: 'Regional',
    Local: 'Local'
} as const;
export type RegionalScope = typeof RegionalScope[keyof typeof RegionalScope];


export function instanceOfRegionalScope(value: any): boolean {
    for (const key in RegionalScope) {
        if (Object.prototype.hasOwnProperty.call(RegionalScope, key)) {
            if (RegionalScope[key as keyof typeof RegionalScope] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RegionalScopeFromJSON(json: any): RegionalScope {
    return RegionalScopeFromJSONTyped(json, false);
}

export function RegionalScopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegionalScope {
    return json as RegionalScope;
}

export function RegionalScopeToJSON(value?: RegionalScope | null): any {
    return value as any;
}

export function RegionalScopeToJSONTyped(value: any, ignoreDiscriminator: boolean): RegionalScope {
    return value as RegionalScope;
}

