/* tslint:disable */
/* eslint-disable */
/**
 * OpenHolidays API v1
 * Open Data API for public and school holidays
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Representation of a subdivision reference
 * @export
 * @interface SubdivisionReference
 */
export interface SubdivisionReference {
    /**
     * Subdivision code
     * @type {string}
     * @memberof SubdivisionReference
     */
    code: string;
    /**
     * Short name for display
     * @type {string}
     * @memberof SubdivisionReference
     */
    shortName: string;
}

/**
 * Check if a given object implements the SubdivisionReference interface.
 */
export function instanceOfSubdivisionReference(value: object): value is SubdivisionReference {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('shortName' in value) || value['shortName'] === undefined) return false;
    return true;
}

export function SubdivisionReferenceFromJSON(json: any): SubdivisionReference {
    return SubdivisionReferenceFromJSONTyped(json, false);
}

export function SubdivisionReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubdivisionReference {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'shortName': json['shortName'],
    };
}

export function SubdivisionReferenceToJSON(json: any): SubdivisionReference {
    return SubdivisionReferenceToJSONTyped(json, false);
}

export function SubdivisionReferenceToJSONTyped(value?: SubdivisionReference | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'shortName': value['shortName'],
    };
}

