/* tslint:disable */
/* eslint-disable */
/**
 * OpenHolidays API v1
 * Open Data API for public and school holidays
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Temporal scope of a holdiay
 * @export
 */
export const TemporalScope = {
    FullDay: 'FullDay',
    HalfDay: 'HalfDay'
} as const;
export type TemporalScope = typeof TemporalScope[keyof typeof TemporalScope];


export function instanceOfTemporalScope(value: any): boolean {
    for (const key in TemporalScope) {
        if (Object.prototype.hasOwnProperty.call(TemporalScope, key)) {
            if (TemporalScope[key as keyof typeof TemporalScope] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TemporalScopeFromJSON(json: any): TemporalScope {
    return TemporalScopeFromJSONTyped(json, false);
}

export function TemporalScopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemporalScope {
    return json as TemporalScope;
}

export function TemporalScopeToJSON(value?: TemporalScope | null): any {
    return value as any;
}

export function TemporalScopeToJSONTyped(value: any, ignoreDiscriminator: boolean): TemporalScope {
    return value as TemporalScope;
}

