import type { WeatherCondition } from '@/hooks/useWeather';
import type { TimeOfDay, TimeVisuals, WeatherVisuals } from './types';

export const WEATHER_VISUALS: Record<WeatherCondition, WeatherVisuals> = {
  clear: {
    cloudColor: '#ffffff',
    cloudOpacity: 0.4,
    turbidity: 0.1,
    rayleigh: 0.5,
    sunPosition: [100, 20, 100],
    ambientIntensity: Math.PI / 1.5,
    speedMultiplier: 1,
    rainIntensity: 0,
    precipitation: 'none',
    cloudCount: 4,
    fogNear: 28,
    fogFar: 90,
    skyMute: 0,
    sunVisibility: 1,
  },
  'partly-cloudy': {
    cloudColor: '#f0f0f0',
    cloudOpacity: 0.7,
    turbidity: 1,
    rayleigh: 1,
    sunPosition: [100, 20, 100],
    ambientIntensity: Math.PI / 2,
    speedMultiplier: 1.2,
    rainIntensity: 0,
    precipitation: 'none',
    cloudCount: 6,
    fogNear: 22,
    fogFar: 75,
    skyMute: 0.08,
    sunVisibility: 0.8,
  },
  overcast: {
    cloudColor: '#88929b',
    cloudOpacity: 0.9,
    turbidity: 10,
    rayleigh: 2,
    sunPosition: [100, 10, 100],
    ambientIntensity: Math.PI / 3,
    speedMultiplier: 0.8,
    rainIntensity: 0,
    precipitation: 'none',
    cloudCount: 8,
    fogNear: 10,
    fogFar: 42,
    skyMute: 0.78,
    sunVisibility: 0.22,
  },
  fog: {
    cloudColor: '#c8d0d4',
    cloudOpacity: 0.75,
    turbidity: 20,
    rayleigh: 4,
    sunPosition: [100, 5, 100],
    ambientIntensity: Math.PI / 4,
    speedMultiplier: 0.3,
    rainIntensity: 0,
    precipitation: 'none',
    cloudCount: 12,
    fogNear: 1.5,
    fogFar: 18,
    skyMute: 0.85,
    sunVisibility: 0.12,
  },
  drizzle: {
    cloudColor: '#66717a',
    cloudOpacity: 0.9,
    turbidity: 12,
    rayleigh: 3,
    sunPosition: [40, 8, 40],
    ambientIntensity: Math.PI / 3.5,
    speedMultiplier: 1.5,
    rainIntensity: 0.16,
    precipitation: 'rain',
    cloudCount: 8,
    fogNear: 9,
    fogFar: 36,
    skyMute: 0.55,
    sunVisibility: 0.18,
  },
  rain: {
    cloudColor: '#303942',
    cloudOpacity: 1,
    turbidity: 18,
    rayleigh: 4,
    sunPosition: [30, 3, 30],
    ambientIntensity: Math.PI / 5,
    speedMultiplier: 2.5,
    rainIntensity: 1,
    precipitation: 'rain',
    cloudCount: 12,
    fogNear: 6,
    fogFar: 30,
    skyMute: 0.68,
    sunVisibility: 0.12,
  },
  snow: {
    cloudColor: '#e0e0e0',
    cloudOpacity: 0.85,
    turbidity: 5,
    rayleigh: 1,
    sunPosition: [100, 15, 100],
    ambientIntensity: Math.PI / 2.5,
    speedMultiplier: 0.5,
    rainIntensity: 0.65,
    precipitation: 'snow',
    cloudCount: 6,
    fogNear: 10,
    fogFar: 42,
    skyMute: 0.28,
    sunVisibility: 0.45,
  },
  thunderstorm: {
    cloudColor: '#2a2a2a',
    cloudOpacity: 1,
    turbidity: 25,
    rayleigh: 5,
    sunPosition: [10, 2, 10],
    ambientIntensity: Math.PI / 8,
    speedMultiplier: 5,
    rainIntensity: 1.55,
    precipitation: 'rain',
    cloudCount: 16,
    fogNear: 4,
    fogFar: 24,
    skyMute: 0.78,
    sunVisibility: 0.05,
  },
};

export const DEFAULT_WEATHER_VISUALS = WEATHER_VISUALS.clear;

export const TIME_VISUALS: Record<TimeOfDay, TimeVisuals> = {
  night: {
    skyColor: '#1a2540',
    zenithColor: '#0f1a30',
    horizonColor: '#2a3a5c',
    sunGlowColor: '#3d4a6a',
    sunPosition: [0, -10, 0],
    ambientIntensity: Math.PI / 8,
    cloudTint: '#2a3a50',
  },
  sunrise: {
    skyColor: '#ff8c42',
    zenithColor: '#1a3a5c',
    horizonColor: '#ff8c42',
    sunGlowColor: '#ffaa55',
    sunPosition: [100, 5, 100],
    ambientIntensity: Math.PI / 3,
    cloudTint: '#ffb366',
  },
  morning: {
    skyColor: '#87ceeb',
    zenithColor: '#4a90e2',
    horizonColor: '#b8d8f0',
    sunGlowColor: '#ffffcc',
    sunPosition: [100, 30, 100],
    ambientIntensity: Math.PI / 2,
    cloudTint: '#ffffff',
  },
  midday: {
    skyColor: '#4a90e2',
    zenithColor: '#2a6bc4',
    horizonColor: '#87ceeb',
    sunGlowColor: '#fffff0',
    sunPosition: [100, 50, 100],
    ambientIntensity: Math.PI / 1.5,
    cloudTint: '#ffffff',
  },
  afternoon: {
    skyColor: '#6ba3d6',
    zenithColor: '#3a7cc4',
    horizonColor: '#a8c8e8',
    sunGlowColor: '#fff5cc',
    sunPosition: [100, 35, 100],
    ambientIntensity: Math.PI / 2,
    cloudTint: '#fff5e6',
  },
  sunset: {
    skyColor: '#ff6b35',
    zenithColor: '#1a2a5c',
    horizonColor: '#ff6b35',
    sunGlowColor: '#ff8844',
    sunPosition: [100, 8, 100],
    ambientIntensity: Math.PI / 3,
    cloudTint: '#ff9966',
  },
  dusk: {
    skyColor: '#4a6a8f',
    zenithColor: '#2a4060',
    horizonColor: '#7a8fa8',
    sunGlowColor: '#e8a070',
    sunPosition: [100, 2, 100],
    ambientIntensity: Math.PI / 5,
    cloudTint: '#6a7a8a',
  },
};
