import type { WeatherCondition } from '@/hooks/useWeather';
import type { TimeOfDay, TimeVisuals, WeatherVisuals } from './types';

export const WEATHER_VISUALS: Record<WeatherCondition, WeatherVisuals> = {
  clear: {
    cloudColor: '#ffffff',
    cloudOpacity: 0.4,
    turbidity: 0.1,
    rayleigh: 0.5,
    sunPosition: [100, 20, 100],
    ambientIntensity: Math.PI / 1.5,
    speedMultiplier: 1,
    rainIntensity: 0,
    cloudCount: 4,
  },
  'partly-cloudy': {
    cloudColor: '#f0f0f0',
    cloudOpacity: 0.7,
    turbidity: 1,
    rayleigh: 1,
    sunPosition: [100, 20, 100],
    ambientIntensity: Math.PI / 2,
    speedMultiplier: 1.2,
    rainIntensity: 0,
    cloudCount: 6,
  },
  overcast: {
    cloudColor: '#b0b0b0',
    cloudOpacity: 0.9,
    turbidity: 10,
    rayleigh: 2,
    sunPosition: [100, 10, 100],
    ambientIntensity: Math.PI / 3,
    speedMultiplier: 0.8,
    rainIntensity: 0,
    cloudCount: 8,
  },
  fog: {
    cloudColor: '#d0d0d0',
    cloudOpacity: 1,
    turbidity: 20,
    rayleigh: 4,
    sunPosition: [100, 5, 100],
    ambientIntensity: Math.PI / 4,
    speedMultiplier: 0.3,
    rainIntensity: 0,
    cloudCount: 10,
  },
  drizzle: {
    cloudColor: '#707070',
    cloudOpacity: 0.9,
    turbidity: 12,
    rayleigh: 3,
    sunPosition: [40, 8, 40],
    ambientIntensity: Math.PI / 3.5,
    speedMultiplier: 1.5,
    rainIntensity: 0.3,
    cloudCount: 8,
  },
  rain: {
    cloudColor: '#3a3a3a',
    cloudOpacity: 1,
    turbidity: 18,
    rayleigh: 4,
    sunPosition: [30, 3, 30],
    ambientIntensity: Math.PI / 5,
    speedMultiplier: 2.5,
    rainIntensity: 1.2,
    cloudCount: 12,
  },
  snow: {
    cloudColor: '#e0e0e0',
    cloudOpacity: 0.85,
    turbidity: 5,
    rayleigh: 1,
    sunPosition: [100, 15, 100],
    ambientIntensity: Math.PI / 2.5,
    speedMultiplier: 0.5,
    rainIntensity: 0,
    cloudCount: 6,
  },
  thunderstorm: {
    cloudColor: '#2a2a2a',
    cloudOpacity: 1,
    turbidity: 25,
    rayleigh: 5,
    sunPosition: [10, 2, 10],
    ambientIntensity: Math.PI / 8,
    speedMultiplier: 5,
    rainIntensity: 2,
    cloudCount: 16,
  },
};

export const DEFAULT_WEATHER_VISUALS = WEATHER_VISUALS.clear;

export const TIME_VISUALS: Record<TimeOfDay, TimeVisuals> = {
  night: {
    skyColor: '#0a1628',
    sunPosition: [0, -10, 0],
    ambientIntensity: Math.PI / 8,
    cloudTint: '#1a2a3a',
  },
  sunrise: {
    skyColor: '#ff8c42',
    sunPosition: [100, 5, 100],
    ambientIntensity: Math.PI / 3,
    cloudTint: '#ffb366',
  },
  morning: {
    skyColor: '#87ceeb',
    sunPosition: [100, 30, 100],
    ambientIntensity: Math.PI / 2,
    cloudTint: '#ffffff',
  },
  midday: {
    skyColor: '#4a90e2',
    sunPosition: [100, 50, 100],
    ambientIntensity: Math.PI / 1.5,
    cloudTint: '#ffffff',
  },
  afternoon: {
    skyColor: '#6ba3d6',
    sunPosition: [100, 35, 100],
    ambientIntensity: Math.PI / 2,
    cloudTint: '#fff5e6',
  },
  sunset: {
    skyColor: '#ff6b35',
    sunPosition: [100, 8, 100],
    ambientIntensity: Math.PI / 3,
    cloudTint: '#ff9966',
  },
  dusk: {
    skyColor: '#2d4a6f',
    sunPosition: [100, 0, 100],
    ambientIntensity: Math.PI / 5,
    cloudTint: '#4a5a6a',
  },
};
